### ISSUE TITLE
Не устанавливается Октопринт. Вываливается с ошибкой при установке argon2-cffi

### ISSUE THREAD

**Issue by MaGr1977** [Nebari-xx/octoprint_installer#6]
Даже если отдельно поставить apt install libffi-dev и саму библиотеку вручную pip3 install argon2-cffi-bindings (она ругнется на неправильно сконфигурированный cffi, переустановит и все-таки встанет в систему) Но при этом, при повторном запуске установки октопринта все тупо виснет на этом моменте:

Collecting argon2-cffi-bindings

Downloading argon2-cffi-bindings-21.2.0.tar.gz (1.8 MB)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 316.7 kB/s eta 0:00:00

Installing build dependencies ... \

Пока система сама не убьет процесс по времени.

**Comment by kaiiiiiiiii** [comment]
`apt install libffi-dev`

Installing this package fixed it for me :)

**Comment by Etherlord** [comment]
Добрый день, постараюсь проверить в выходные, если проблема еще актуальна

**Comment by MaGr1977** [comment]
Добрый. Не нужно. OPI была на 256мб. Там своп по умолчанию 128мб. Для сборки не хватало. Увеличение до 256мб решило проблему.
