### ISSUE TITLE
how to locate webcamDaemon file

### ISSUE THREAD

**Issue by dodolcool** [Nebari-xx/octoprint_installer#7]
Hello i have an issue with my webcam. when seeing your webcamDaemon script i notice the path to the webcam is dev/vidoe0. in my device video 0 is occupied by hdmi and i need to use video1 but i cant find the file any where. i tried to make the file manually  but its still not work. can you help with this issue?

ps my linux level is just copy modify and paste >.<

**Comment by Etherlord** [comment]
Hello, you can find the script at /usr/local/bin/webcamDaemon
